Refactor backend code
Dogacel/Kalas-Iris pull request #53
Opened 2021-02-03 00:04 UTC by Dogacel

Closes #43

2021-02-03 13:00 UTC, AtaAtasoy requested changes

2021-02-03 13:00 UTC, AtaAtasoy commented on api/flaskr/routes/image.py
> +    return 'Done!'
IMO, a Response object with a status code or a JSON response would be better.

2021-02-03 13:00 UTC, AtaAtasoy commented on api/flaskr/routes/auth.py
> +            return jsonify(tokens), 200
is it possible to edit this line as ?
```python
return Response(tokens, status=200)
```
or 
```python
return Response(jsonify(tokens), status=200)
```
I'm not sure which one of the two lines of code would work, thus I suggested both. I think you get the idea 😄 

I also think returning a Response object in each of the routes would make our code more consistent.

2021-02-03 13:00 UTC, AtaAtasoy commented on api/flaskr/routes/auth.py
> +    return jsonify({"msg": "Successfully logged out"}), 200
Is it possible to wrap this return value around Response() object ? Maybe we should change one of the return values and test it before we change every single response with Response().

2021-02-08 13:33 UTC, Dogacel commented
@AtaAtasoy I removed 200 because it is the default status for a response object.

2021-02-08 13:58 UTC, AtaAtasoy approved these changes
Looks good. Eline saglik 😸

2021-02-08 13:58 UTC, merged